// lib/courses.ts
// ─────────────────────────────────────────────────────────────────────────────
// Central data source for all courses.
// Add a new entry here → it automatically appears in CoursesSection.
// In production, replace this array with a database / CMS / API call.
// ─────────────────────────────────────────────────────────────────────────────

import { Course } from "@/components/mainComponents/Coursecard";

export const courses: Course[] = [
  {
    id: "mba-international",
    badge: "Local",
    title: "Master of Business Administration – International",
    subtitle: "MBA",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/mba-international",
  },
  {
    id: "mba-health-social-care",
    badge: "Local",
    title: "Master of Business Administration – Health and Social Care",
    subtitle: "MBA",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/mba-health-social-care",
  },
  {
    id: "mba-online",
    badge: "Local",
    title: "Master of Business Administration Online",
    subtitle: "MBA",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/mba-online",
  },
  {
    id: "msc-international-management-online",
    badge: "Local",
    title: "International Management Online",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-international-management-online",
  },
  {
    id: "msc-hospitality-tourism",
    badge: "Local",
    title: "International Hospitality and Tourism Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-international-hospitality-tourism-management",
  },
  {
    id: "msc-international-marketing",
    badge: "Local",
    title: "International Marketing",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-international-marketing",
  },
  {
    id: "msc-international-project-management",
    badge: "Local",
    title: "International Project Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-international-project-management",
  },
  {
    id: "msc-programme-project-management",
    badge: "Local",
    title: "Programme and Project Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-programme-project-management",
  },
  {
    id: "msc-accounting-financial-management",
    badge: "Local",
    title: "Accounting and Financial Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-accounting-financial-management",
  },
  {
    id: "msc-international-business-management",
    badge: "Local",
    title: "International Business Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-international-business-management",
  },
  {
    id: "msc-business-analytics",
    badge: "Local",
    title: "Business with Business Analytics",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-analytics",
  },
  {
    id: "msc-business-entrepreneurship",
    badge: "Local",
    title: "Business with Entrepreneurship",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-entrepreneurship",
  },
  {
    id: "msc-business-financial-management",
    badge: "Local",
    title: "Business with Financial Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-financial-management",
  },
  {
    id: "msc-business-hospitality-tourism",
    badge: "Local",
    title: "Business with Hospitality and Tourism Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-hospitality-tourism",
  },
  {
    id: "msc-business-hr",
    badge: "Local",
    title: "Business with Human Resource Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-human-resource-management",
  },
  {
    id: "msc-business-international-management",
    badge: "Local",
    title: "Business with International Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-international-management",
  },
  {
    id: "msc-business-marketing-management",
    badge: "Local",
    title: "Business with Marketing Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-business-marketing-management",
  },
  {
    id: "msc-computing-technology",
    badge: "Local",
    title: "Computing and Technology",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-computing-technology",
  },
  {
    id: "msc-artificial-intelligence",
    badge: "Local",
    title: "Artificial Intelligence Technology",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-artificial-intelligence-technology",
  },
  {
    id: "msc-big-data-science",
    badge: "Local",
    title: "Big Data and Data Science Technology",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-big-data-science-technology",
  },
  {
    id: "msc-cyber-security",
    badge: "Local",
    title: "Cyber Security",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-cyber-security",
  },
  {
    id: "msc-cyber-security-technology",
    badge: "Local",
    title: "Cyber Security Technology",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-cyber-security-technology",
  },
  {
    id: "msc-digital-marketing",
    badge: "Local",
    title: "Digital Marketing",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-digital-marketing",
  },
  {
    id: "msc-global-logistics",
    badge: "Local",
    title: "Global Logistics, Operations and Supply Chain Management",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-global-logistics-supply-chain",
  },
  {
    id: "msc-global-logistics-online",
    badge: "Local",
    title: "Global Logistics, Operations and Supply Chain Management Online",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-global-logistics-supply-chain-online",
  },
  {
    id: "msc-social-care-health-wellbeing",
    badge: "Local",
    title: "Social Care, Health and Wellbeing",
    subtitle: "MSc",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/msc-social-care-health-wellbeing",
  },
  {
    id: "master-public-health",
    badge: "Local",
    title: "Master of Public Health",
    subtitle: "MPH",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/master-public-health",
  },
  {
    id: "llm-international-law",
    badge: "Local",
    title: "International Law",
    subtitle: "LLM",
    duration: "4 Years",
    schedule: "Weekdays/Weekends",
    href: "/courses/llm-international-law",
  },
];