// lib/undergraduate.ts
// ─────────────────────────────────────────────────────────────────────────────
// Central data source for all undergraduate courses.
// Add a new entry here → it automatically appears in CoursesSection.
// In production, replace this array with a database / CMS / API call.
// ─────────────────────────────────────────────────────────────────────────────

import { Course } from "@/components/mainComponents/Coursecard";

export const courses: Course[] = [
  {
    id: "business-tourism",
    title: "Business and Tourism Management",
    subtitle: "BSc (Hons)",
    duration: "3 Year Degree",
    href: "/courses/business-tourism-management",
  },
  {
    id: "business-financial",
    title: "Business and Financial Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-financial-management",
  },
  {
    id: "business-hospitality",
    title: "Business, Hospitality and Events Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-hospitality-events-management",
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing and Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/digital-marketing-management",
  },
  {
    id: "finance-accounting",
    title: "Finance and Accounting",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/finance-accounting",
  },
  {
    id: "international-business",
    title: "International Business Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/international-business-management",
  },
  {
    id: "business-hr",
    title: "Business and Human Resource Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-human-resource-management",
  },
  {
    id: "business-law",
    title: "Business and Law",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-law",
  },
  {
    id: "law",
    title: "Law",
    subtitle: "LLB (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/law",
  },
  {
    id: "health-social-care",
    title: "Health and Social Care",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/health-social-care",
  },
  {
    id: "psychology",
    title: "Psychology",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/psychology",
  },
  {
    id: "mental-health",
    title: "Mental Health and Wellbeing",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/mental-health-wellbeing",
  },
  {
    id: "public-health",
    title: "Public Health",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/public-health",
  },
  {
    id: "business-marketing",
    title: "Business and Marketing",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-marketing",
  },
  {
    id: "business-enterprise",
    title: "Business Enterprise and Innovation Management",
    subtitle: "BSc (Hons)",
    duration: "3 Year Degree",
    href: "/courses/business-enterprise-innovation-management",
  },
  {
    id: "business-management-bsc-hons",
    title: "Business Management",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-management-bsc-hons",
  },
  {
    id: "business-management-ba-hons",
    title: "Business Management",
    subtitle: "BA (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-management-ba-hons",
  },
  {
    id: "business-management-bsc",
    title: "Business Management",
    subtitle: "BSc",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/business-management-bsc",
  },
  {
    id: "computing-hons",
    title: "Computing",
    subtitle: "BSc (Hons)",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/computing-hons",
  },
  {
    id: "computing",
    title: "Computing",
    subtitle: "BSc",
    duration: "3 Years / 4 Years (with Foundation Year)",
    href: "/courses/computing",
  },
  {
    id: "computer-science",
    title: "Computer Science",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computer-science",
  },
  {
    id: "computing-ai",
    title: "Computing with Artificial Intelligence Technology",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computing-artificial-intelligence",
  },
  {
    id: "computing-cyber",
    title: "Computing with Cyber Security Technology",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computing-cyber-security",
  },
  {
    id: "computing-data-science",
    title: "Computing with Data Science and Big Data Technology",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computing-data-science",
  },
  {
    id: "computing-it-management",
    title: "Computing with Information Technology Management",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computing-it-management",
  },
  {
    id: "computing-technology",
    title: "Computing with Technology",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/computing-technology",
  },
  {
    id: "cyber-security",
    title: "Cyber Security",
    subtitle: "BSc",
    duration: "3 Year Degree",
    href: "/courses/cyber-security",
  },
  {
    id: "data-science",
    title: "Data Science",
    subtitle: "BSc (Hons)",
    duration: "3 Year Degree",
    href: "/courses/data-science",
  },
  {
    id: "construction-management",
    title: "Construction Management",
    subtitle: "BSc (Hons)",
    duration: "3 Year Degree",
    href: "/courses/construction-management",
  },
  {
    id: "software-engineering",
    title: "Software Engineering",
    subtitle: "BEng (Hons)",
    duration: "3 Year Degree",
    href: "/courses/software-engineering",
  },
  {
    id: "electrical-engineering",
    title: "Electrical and Electronic Engineering",
    subtitle: "BEng (Hons)",
    duration: "3 Year Degree",
    href: "/courses/electrical-electronic-engineering",
  },
  {
    id: "mechanical-engineering",
    title: "Mechanical Engineering",
    subtitle: "BEng (Hons)",
    duration: "3 Year Degree",
    href: "/courses/mechanical-engineering",
  },
];